version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx book/"

python:
   install:
   - requirements: book/requirements.txt

sphinx:
  builder: html
  # fail on warning is false until i get the API doc build sorted out
  fail_on_warning: false

formats:
  - pdf
