version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx book/"

conda:
  environment: https://raw.githubusercontent.com/qiime2/distributions/dev/latest/passed/qiime2-tiny-ubuntu-latest-conda.yml

sphinx:
  builder: html
  # fail on warning is false until i get the API doc build sorted out
  fail_on_warning: false

formats:
  - pdf
